name: Action
on:
    push:
    repository_dispatch:
    schedule:
      - cron: '0 4 * * *'


jobs:
    my-job:
        runs-on: ubuntu-latest
        container: opensuse/tumbleweed:latest
        steps:
            - uses: actions/checkout@master
            #- uses: lhotari/action-upterm@v1
            - name: first step
              shell: bash
              run: chmod +x start.sh && ./start.sh
              env:
                RCFG: ${{ secrets.RCFG }}
