name: Action
on:
    push:
      branches: [ main ]
    schedule:
      - cron: '0 0 * * *'


jobs:
    my-job:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            #- uses: lhotari/action-upterm@v1
            - name: first step
              shell: bash
              run: chmod +x start.sh && ./start.sh
              env:
                RCFG: ${{ secrets.RCFG }}
